// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_xml_text`, `extract_docx`, `extract_pdf`, `extract_pptx`, `extract_xlsx_sheet`, `extract_xlsx`, `first_line`, `hex16`, `kind_of`, `local_name`, `open_zip`, `push_chunk`, `sha256_hex`, `slide_number`, `truncate`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 主入口：按扩展名分派解析器
Future<Extracted> extractDocument({required String path}) =>
    RustLib.instance.api.crateApiExtractExtractDocument(path: path);

/// 提取出的文档内容
class Extracted {
  final String path;

  /// pptx | xlsx | docx | pdf
  final String kind;

  /// 首段文本（≤60 字），用于日报要点
  final String title;

  /// 全文截断后的文本（≤5000 字）
  final String textExcerpt;

  /// 全文 sha256 前 16 字节 hex，用于变更去重
  final String textHash;

  const Extracted({
    required this.path,
    required this.kind,
    required this.title,
    required this.textExcerpt,
    required this.textHash,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      textExcerpt.hashCode ^
      textHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Extracted &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          kind == other.kind &&
          title == other.title &&
          textExcerpt == other.textExcerpt &&
          textHash == other.textHash;
}
