// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_listener`, `parse_code`, `parse_modifiers`

/// 注册全局热键。[id] 由 Dart 侧生成并传入（FRB stream 模式吞返回值，
/// 调用方需要 id 做注销），事件触发时通过 [stream] 转发 [id]。
Stream<int> registerHotkey({
  required BigInt id,
  required List<String> modifiers,
  required String key,
}) => RustLib.instance.api.crateApiHotkeyRegisterHotkey(
  id: id,
  modifiers: modifiers,
  key: key,
);

/// 注销热键
Future<void> unregisterHotkey({required BigInt id}) =>
    RustLib.instance.api.crateApiHotkeyUnregisterHotkey(id: id);
